version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3.8'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
    ports:
      - "127.0.0.1:8888:8888" # ここを変更していく